// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `npm run generate-audio` to regenerate.

export const audioMap = {
  "Hmm, I wonder! A sign says '25% OFF' a $20 toy. How much do you actually save?": "assets/audio/audio_hmm_i_wonder_a_sign_says_25_off_a_20_toy_how_much_do_yo_0.mp3",
  "Percent tells us a part of the price — but what part?": "assets/audio/audio_percent_tells_us_a_part_of_the_price_but_what_part_1.mp3",
  "Hmm, I wonder! In Priya's class, 8 out of 10 students voted for pizza. What percent is that?": "assets/audio/audio_hmm_i_wonder_in_priyas_class_8_out_of_10_students_voted_2.mp3",
  "Percent means 'out of 100' — even when the total isn't 100!": "assets/audio/audio_percent_means_out_of_100_even_when_the_total_isnt_100_3.mp3",
  "Hmm, I wonder! A goalie saved 18 out of 20 shots. Is that a good percentage?": "assets/audio/audio_hmm_i_wonder_a_goalie_saved_18_out_of_20_shots_is_that__4.mp3",
  "Percentages help us compare performance fairly!": "assets/audio/audio_percentages_help_us_compare_performance_fairly_5.mp3",
  "Hmm, I wonder! If a glass is 0.5 full, what percent full is that?": "assets/audio/audio_hmm_i_wonder_if_a_glass_is_05_full_what_percent_full_is_6.mp3",
  "Decimals and percents are just two ways of writing the same amount!": "assets/audio/audio_decimals_and_percents_are_just_two_ways_of_writing_the__7.mp3",
  "Hmm, I wonder! How do we turn a fraction like 3/4 into a percent?": "assets/audio/audio_hmm_i_wonder_how_do_we_turn_a_fraction_like_34_into_a_p_8.mp3",
  "Hint: what do 3/4 and 75/100 have in common?": "assets/audio/audio_hint_what_do_34_and_75100_have_in_common_9.mp3",
  "Priya's class has a booth at the school fair, selling stickers! They made exactly 100 stickers to sell — a nice round number. By lunchtime, 42 of the 100 stickers are sold. Dev wants to tell everyone how the booth is doing, but saying 42 out of 100 every time feels clunky. Priya wonders... is there a simpler way to describe this amount? Let's help Priya and Dev!": "assets/audio/audio_priyas_class_has_a_booth_at_the_school_fair_selling_sti_10.mp3",
  "We can use percent! says Priya. Percent means per hundred — it tells us how many out of every 100. Since exactly 42 of the 100 stickers are sold, that's 42 percent. Percent lets us describe and compare parts of a whole using the very same friendly scale of 100, every time. Percent means out of 100!": "assets/audio/audio_we_can_use_percent_says_priya_percent_means_per_hundred_11.mp3",
  "Dev shows the connection: 42 percent is the same amount as the fraction 42 over 100, and the decimal 0.42. Whether we write it as a fraction, a decimal, or a percent, says Dev, it's still the exact same amount — just written in a different way! Percent, fraction, decimal — same amount!": "assets/audio/audio_dev_shows_the_connection_42_percent_is_the_same_amount__12.mp3",
  "By the end of the fair, Priya and Dev could describe every booth's sales using percentages. Now let's practice finding percentages of all kinds of amounts. Are you ready? Your turn now!": "assets/audio/audio_by_the_end_of_the_fair_priya_and_dev_could_describe_eve_13.mp3",
  "Station one — Percent on the Grid! A line marks a percent between two benchmarks. Tap the benchmark it's closest to. Let's go!": "assets/audio/audio_station_one_percent_on_the_grid_a_line_marks_a_percent__14.mp3",
  "Station two — Percent Grid Spotlight! Look at the shaded grid. Find how many of the 100 squares are shaded. Look carefully!": "assets/audio/audio_station_two_percent_grid_spotlight_look_at_the_shaded_g_15.mp3",
  "Final station — Percent It Out! You will see a percent-of-a-number problem to solve. Use the number pad to type your answer. You've got this!": "assets/audio/audio_final_station_percent_it_out_you_will_see_a_percentofan_16.mp3",
  "The Boss Battle begins! Answer the questions correctly to defeat the boss and claim your Percent Pro trophy!": "assets/audio/audio_the_boss_battle_begins_answer_the_questions_correctly_t_17.mp3",
  "You defeated the boss! The Golden Percent Trophy is yours!": "assets/audio/audio_you_defeated_the_boss_the_golden_percent_trophy_is_your_18.mp3",
  "Let's explore understanding percentages!": "assets/audio/audio_lets_explore_understanding_percentages_19.mp3",
};
